# Generated by Django 3.1.5 on 2021-01-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.SlugField(default='robotics', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(default='nisky', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
