# Generated by Django 2.2.2 on 2019-08-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0002_auto_20190812_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='subforum',
            name='url_name',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
