# Generated by Django 2.2.2 on 2019-08-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0003_subforum_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subforum',
            name='url_name',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
