# Generated by Django 2.2.2 on 2019-08-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0005_auto_20190815_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subforum',
            name='url_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
