# Generated by Django 2.2.2 on 2019-08-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0006_auto_20190815_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subforum',
            name='url_name',
        ),
        migrations.AddField(
            model_name='subforum',
            name='_url_name',
            field=models.CharField(blank=True, db_column='url_name', max_length=30, null=True),
        ),
    ]
