# Generated by Django 2.2.2 on 2019-08-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0007_auto_20190816_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subforum',
            name='_url_name',
        ),
        migrations.AddField(
            model_name='subforum',
            name='url_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
