# Generated by Django 2.2.2 on 2019-08-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0008_auto_20190816_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subforum',
            name='url_name',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
