# Generated by Django 2.2.2 on 2019-08-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0009_auto_20190816_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subforum',
            old_name='name',
            new_name='_name',
        ),
        migrations.RenameField(
            model_name='subforum',
            old_name='url_name',
            new_name='_url_name',
        ),
        migrations.AlterField(
            model_name='subforum',
            name='_name',
            field=models.CharField(db_column='name', max_length=20),
        ),
        migrations.AlterField(
            model_name='subforum',
            name='_url_name',
            field=models.CharField(blank=True, db_column='url_name', default='', max_length=25),
        ),
    ]
