# Generated by Django 2.2.2 on 2019-08-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0010_auto_20190816_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subforum',
            old_name='_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='subforum',
            name='_url_name',
        ),
        migrations.AddField(
            model_name='subforum',
            name='url_name',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
