# Generated by Django 2.2.2 on 2019-08-19 22:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0011_auto_20190816_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='up_votes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='up_votes',
        ),
    ]
