# Generated by Django 2.2.2 on 2019-08-22 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0014_post_downvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downvote_html_classes',
            field=models.ManyToManyField(blank=True, related_name='post_downvote_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='upvote_html_classes',
            field=models.ManyToManyField(blank=True, related_name='post_upvote_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
