# Generated by Django 2.2.2 on 2019-08-24 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0015_auto_20190822_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='downvote_html_classes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvote_html_classes',
        ),
    ]
