# Generated by Django 2.2.4 on 2019-09-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0017_auto_20190826_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
