# Generated by Django 2.2.4 on 2019-09-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0018_auto_20190907_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('class_grade', models.IntegerField()),
                ('class_placement', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='subforum',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.AddField(
            model_name='post',
            name='grade',
            field=models.CharField(default=11, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='placement',
            field=models.CharField(default='R', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(default='General', max_length=50),
            preserve_default=False,
        ),
    ]
