# Generated by Django 2.2.4 on 2019-09-07 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0019_auto_20190907_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='user_school_classes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
