# Generated by Django 2.2.4 on 2019-09-07 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0020_schoolclass_user_school_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolclass',
            old_name='user_school_classes',
            new_name='class_students',
        ),
    ]
