# Generated by Django 2.2.4 on 2019-09-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0021_auto_20190907_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='class_teachers',
            field=models.CharField(default='Nobody', max_length=50),
            preserve_default=False,
        ),
    ]
