# Generated by Django 2.2.4 on 2019-09-07 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0023_auto_20190907_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='post',
            name='placement',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='class_students',
            field=models.ManyToManyField(blank=True, related_name='class_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='class_teachers',
            field=models.ManyToManyField(blank=True, related_name='class_teachers', to=settings.AUTH_USER_MODEL),
        ),
    ]
