# Generated by Django 2.2.4 on 2019-09-07 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0026_auto_20190907_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='text',
        ),
    ]
