# Generated by Django 2.2.4 on 2019-09-07 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0027_auto_20190907_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forum.SchoolClass'),
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='class_teachers',
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_teachers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT,
                                    to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
