# Generated by Django 2.2.4 on 2019-09-07 22:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0028_auto_20190907_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolclass',
            old_name='class_teachers',
            new_name='class_teacher',
        ),
    ]
