# Generated by Django 2.2.4 on 2019-09-13 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0031_auto_20190907_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sub_forum',
        ),
        migrations.AddField(
            model_name='post',
            name='school_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='post_schoolclass', to='forum.SchoolClass'),
        ),
    ]
