# Generated by Django 2.2.4 on 2019-09-29 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0032_auto_20190913_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_school_class',
        ),
    ]
