# Generated by Django 2.2.4 on 2019-09-29 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0033_remove_post_post_school_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolclass',
            old_name='class_grade',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='schoolclass',
            old_name='class_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='schoolclass',
            old_name='class_placement',
            new_name='placement',
        ),
        migrations.RenameField(
            model_name='schoolclass',
            old_name='class_students',
            new_name='students',
        ),
        migrations.RenameField(
            model_name='schoolclass',
            old_name='class_teacher',
            new_name='teacher',
        ),
    ]
