# Generated by Django 2.2.4 on 2019-09-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0035_auto_20190929_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='grade',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='placement',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='subject',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
