# Generated by Django 2.2.4 on 2019-09-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0036_auto_20190929_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='grade',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
