# Generated by Django 2.2.4 on 2019-10-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0037_auto_20190929_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=10000),
        ),
    ]
