# Generated by Django 2.2.2 on 2019-07-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190722_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_tag',
            field=models.IntegerField(default=1000),
        ),
    ]
