# Generated by Django 3.1 on 2020-10-24 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='main_img',
            new_name='img',
        ),
    ]
