# Generated by Django 3.0.8 on 2020-08-05 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('XroadsAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='schools',
            field=models.ManyToManyField(to='XroadsAPI.School'),
        ),
        migrations.AddField(
            model_name='club',
            name='meeting_days',
            field=models.ManyToManyField(blank=True, to='XroadsAPI.MeetDay'),
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='slides',
            field=models.ManyToManyField(blank=True, to='XroadsAPI.Slide'),
        ),
    ]
