# Generated by Django 3.0.8 on 2020-08-12 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('XroadsAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XroadsAPI.School'),
        ),
    ]
