# Generated by Django 3.0.8 on 2020-07-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_anon',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
