# Generated by Django 3.0.8 on 2020-07-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0002_auto_20200719_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
