# Generated by Django 3.0.8 on 2020-07-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0002_auto_20200730_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchyperms',
            name='perm_name',
            field=models.CharField(max_length=200),
        ),
    ]
