# Generated by Django 3.1 on 2020-10-24 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0002_auto_20201024_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='contact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='club_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FeaturedClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_curr_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curr_club', to='XroadsAPI.club')),
                ('_next_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_club', to='XroadsAPI.club')),
                ('featured', models.ManyToManyField(related_name='featured_club', to='XroadsAPI.Club')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XroadsAPI.school')),
            ],
        ),
    ]
