# Generated by Django 3.0.8 on 2020-07-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0002_auto_20200721_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_anon',
            field=models.BooleanField(default=False),
        ),
    ]
