# Generated by Django 3.1 on 2020-10-24 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0003_auto_20201024_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='_curr_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curr_club', to='XroadsAPI.club'),
        ),
        migrations.AddField(
            model_name='school',
            name='_next_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_club', to='XroadsAPI.club'),
        ),
        migrations.AddField(
            model_name='school',
            name='featured',
            field=models.ManyToManyField(related_name='featured_club', to='XroadsAPI.Club'),
        ),
        migrations.DeleteModel(
            name='FeaturedClub',
        ),
    ]
