# Generated by Django 3.0.8 on 2020-07-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0003_auto_20200719_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='_phone',
            new_name='phone',
        ),
    ]
