# Generated by Django 3.1 on 2020-09-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0003_districtdomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='meeting_days',
        ),
        migrations.DeleteModel(
            name='MeetDay',
        ),
    ]
