# Generated by Django 3.1 on 2020-09-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0004_auto_20200905_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='join_promo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
