# Generated by Django 3.0.8 on 2020-07-22 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0004_auto_20200722_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='meeting_days',
            field=models.ManyToManyField(blank=True, to='XroadsAPI.MeetDay'),
        ),
        migrations.AlterField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='slides',
            field=models.ManyToManyField(blank=True, to='XroadsAPI.Slide'),
        ),
    ]
