# Generated by Django 3.1 on 2020-10-29 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0005_auto_20201024_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='_curr_club',
        ),
        migrations.RemoveField(
            model_name='school',
            name='_next_club',
        ),
        migrations.AddField(
            model_name='club',
            name='featured_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RemoveField(
            model_name='school',
            name='featured',
        ),
        migrations.AddField(
            model_name='school',
            name='featured',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured', to='XroadsAPI.club'),
        ),
    ]
