# Generated by Django 3.0.8 on 2020-07-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0005_club_faq_meetday_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
