# Generated by Django 3.0.8 on 2020-07-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0006_auto_20200720_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetday',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'MON'), ('TUESDAY', 'MON'), ('WEDNESDAY', 'MON'), ('THURSDAY', 'MON'), ('FRIDAY', 'MON'), ('SATURDAY', 'MON'), ('SUNDAY', 'MON'), ('CUSTOM', 'MON')], default='CUSTOM', max_length=15),
        ),
    ]
