# Generated by Django 3.1 on 2020-11-01 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0006_auto_20201029_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='featured_order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='featured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured', to='XroadsAPI.club'),
        ),
    ]
