# Generated by Django 3.0.8 on 2020-07-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0007_auto_20200720_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='faq',
            field=models.ManyToManyField(blank=True, to='XroadsAPI.Faq'),
        ),
        migrations.AlterField(
            model_name='club',
            name='meeting_days',
            field=models.ManyToManyField(blank=True, to='XroadsAPI.MeetDay'),
        ),
        migrations.AlterField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, to='XroadsAPI.Profile'),
        ),
        migrations.AlterField(
            model_name='club',
            name='slides',
            field=models.ManyToManyField(blank=True, to='XroadsAPI.Slide'),
        ),
        migrations.AlterField(
            model_name='meetday',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=15),
        ),
    ]
