# Generated by Django 3.1 on 2020-09-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0007_auto_20200917_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
