# Generated by Django 3.0.8 on 2020-07-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0008_auto_20200720_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='commitment',
            new_name='hours',
        ),
    ]
