# Generated by Django 3.0.8 on 2020-07-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0009_auto_20200720_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='faq',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
