# Generated by Django 3.0.8 on 2020-07-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0010_auto_20200720_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='')),
                ('clubs', models.ManyToManyField(to='XroadsAPI.Club')),
                ('students', models.ManyToManyField(to='XroadsAPI.Profile')),
            ],
        ),
    ]
