# Generated by Django 3.1 on 2020-11-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0010_auto_20201111_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
    ]
