# Generated by Django 3.0.8 on 2020-07-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0011_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='faq',
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
