# Generated by Django 3.1 on 2020-11-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0011_auto_20201111_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='requested_count',
            field=models.IntegerField(default=0),
        ),
    ]
