# Generated by Django 3.1 on 2020-11-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0012_auto_20201111_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='requested_count',
            new_name='views',
        ),
    ]
