# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-2.0.4
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: xroads-pod
  name: xroads-pod
spec:
  containers:
  - name: nginx
    ports:
    - containerPort: 80
      hostPort: 9999
      protocol: TCP
    command:
    - nginx
    - -g
    - daemon off;
    image: localhost/django_nginx
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /usr/src/app/static
      name: home-polrtex-projects-XRoads-deploy-staticfiles
    - mountPath: /usr/src/app/reactapp
      name: home-polrtex-projects-XRoads-xroads-react-build
    - mountPath: /usr/src/app/media
      name: home-polrtex-projects-XRoads-xroads_django-media
    workingDir: /

  - name: gunicorn
    image: localhost/django_gunicorn
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /home/xroads/xroads_dj
    env:
      - name: DB_HOST
        value: "192.168.99.243"
      - name: DB_PASS
        value: "PTUvEj9Bh9P2"
      - name: CORS_ALLOWED_ORIGINS
        value: "http://app.xroads.local:9999"
      - name: ALLOWED_HOSTS
        value: "app.xroads.local"
      - name: DJANGO_DEBUG
        value: "True"
  volumes:   
  - hostPath:
      path: /home/polrtex/projects/XRoads/deploy/staticfiles
      type: Directory
    name: home-polrtex-projects-XRoads-deploy-staticfiles
  - hostPath:
      path: /home/polrtex/projects/XRoads/xroads-react/build
      type: Directory
    name: home-polrtex-projects-XRoads-xroads-react-build
  - hostPath:
      path: /home/polrtex/projects/XRoads/xroads_django/media
      type: Directory
    name: home-polrtex-projects-XRoads-xroads_django-media
status: {}
---
metadata:
  creationTimestamp: null
spec: {}
status:
  loadBalancer: {}

