# Generated by Django 3.0.8 on 2020-08-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hierarchy_perms',
            field=models.ManyToManyField(blank=True, to='XroadsAuth.HierarchyPerms'),
        ),
    ]
