# Generated by Django 3.1 on 2020-08-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAPI', '0003_districtdomain'),
        ('XroadsAuth', '0003_auto_20200821_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='XroadsAPI.district'),
        ),
    ]
