# Generated by Django 3.1 on 2020-09-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XroadsAuth', '0007_inviteduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteduser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
